import http from 'node:http';
import fs from 'node:fs';
import { Store, POINT_PLANS, pointPlanById, drawLogCsv, cardCsv, paymentCsv, shipmentLabelCsv, publicCard, publicUser } from './store.js';

const store = new Store();
const port = Number(process.env.PORT || 3000);
const indexHtml = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
const surfaceHtml = surface => indexHtml.replace('<html lang="ja">', `<html lang="ja" data-surface="${surface}">`);
const json = (res, status, body) => { res.writeHead(status, {'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}); res.end(JSON.stringify(body)); };
const body = req => new Promise((resolve, reject) => { let data=''; req.on('data', c => { data += c; if (data.length > 1e6) reject(new Error('request too large')); }); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(new Error('invalid JSON')); } }); req.on('error', reject); });
const token = req => (req.headers.authorization || '').replace(/^Bearer\s+/i, '');
const clientIp = req => String(process.env.TRUST_PROXY === 'true' ? (req.headers['x-forwarded-for'] || req.socket.remoteAddress || 'unknown') : (req.socket.remoteAddress || 'unknown')).split(',')[0].trim();
const environment = process.env.ADMIN_ENV === 'production' ? 'production' : 'development';
function requireUser(req, res) { const user = store.userForToken(token(req)); if (!user) { json(res, 401, {error:'authentication required'}); return null; } return user; }
function requireAdmin(req, res, { roles = ['owner', 'operator', 'viewer'] } = {}) {
  const admin = store.adminForToken(token(req), { ip: clientIp(req), environment });
  if (!admin) { json(res,401,{error:'admin 2FA authentication required'}); return null; }
  if (!roles.includes(admin.role)) { json(res,403,{error:'insufficient admin role'}); return null; }
  return admin;
}
function audit(admin, req, action, target, before, after, reason = '', options) { return store.appendAudit({ actor: admin.id, action, target, before, after, ip: clientIp(req), reason }, options); }
function adminBodyError(bodyValue, { reasonRequired = false, destructive = false } = {}) {
  if (reasonRequired && (!bodyValue.reason || typeof bodyValue.reason !== 'string' || !bodyValue.reason.trim())) throw new Error('operation reason is required');
  if (destructive && environment === 'production' && bodyValue.confirmProduction !== true) throw new Error('production confirmation is required');
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); const path = url.pathname;
    if (req.method === 'GET' && path === '/api/packs') return json(res,200,{packs:store.publicPacks().filter(p=>p.status==='selling')});
    if (req.method === 'GET' && path.startsWith('/api/packs/')) { const packId=path.split('/').pop(); const p=store.publicPacks().find(x=>x.id===packId && x.status==='selling'); return p ? json(res,200,{pack:p, odds:store.packOdds(p.id), lineup:store.packLineup(p.id)}) : json(res,404,{error:'pack not found'}); }
    if (req.method === 'POST' && path === '/api/auth/register') { const u=store.register(await body(req)); return json(res,201,{user:publicUser(u)}); }
    if (req.method === 'POST' && path === '/api/auth/login') { const b=await body(req); return json(res,200,store.login(b.email,b.password)); }
    if (req.method === 'POST' && path === '/api/admin/auth/login') { const b=await body(req); return json(res,200,store.adminLogin(b.email,b.password,b.otp,{ip:clientIp(req),environment})); }
    if (req.method === 'POST' && path === '/api/admin/auth/logout') { store.adminLogout(token(req)); return json(res,204,{}); }
    if (req.method === 'GET' && path === '/api/admin/environment') { const admin=requireAdmin(req,res); return admin && json(res,200,{environment,production:environment==='production',headerColor:environment==='production'?'#b91c1c':'#166534'}); }
    if (req.method === 'POST' && path === '/api/auth/logout') { if (token(req)) { store.logout(token(req)); store.adminLogout(token(req)); } return json(res,204,{}); }
    if (req.method === 'GET' && path === '/api/me') { const u=store.userForToken(token(req)); if (u) return json(res,200,{user:publicUser(u)}); const admin=store.adminForToken(token(req),{ip:clientIp(req),environment}); return admin ? json(res,200,{user:{...publicUser(admin.user),role:admin.role}}) : json(res,401,{error:'authentication required'}); }
    if (req.method === 'POST' && path === '/api/admin/points') { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); const result=await store.adjustPointsByAdmin({userId:b.userId,amount:Number(b.amount),reason:b.reason,adminId:u.id,ip:clientIp(req)}); return json(res,200,result); }
    if (req.method === 'POST' && path === '/api/draw') { const u=requireUser(req,res); if(!u)return; const b=await body(req); const quantity = b.quantity === 'all' ? store.publicPacks().find(p=>p.id===b.packId)?.remaining : Number(b.quantity || 1); return json(res,200,await store.draw(u.id,b.packId,quantity)); }
    if (req.method === 'GET' && path === '/api/cards') { const u=requireUser(req,res); return u && json(res,200,{cards:store.publicCards(u.id)}); }
    if (req.method === 'POST' && path === '/api/cards/redeem') { const u=requireUser(req,res); if(!u)return; const b=await body(req); return json(res,200,await store.redeemMany(u.id,b.userCardIds)); }
    if (req.method === 'POST' && path.startsWith('/api/cards/') && path.endsWith('/redeem')) { const u=requireUser(req,res); if(!u)return; const id=path.split('/')[3]; return json(res,200,await store.redeem(u.id,id)); }
    if (req.method === 'GET' && path === '/api/transactions') { const u=requireUser(req,res); return u && json(res,200,{transactions:store.state.pointTransactions.filter(x=>x.userId===u.id)}); }
    if (req.method === 'GET' && path === '/api/point-plans') return json(res,200,{plans:POINT_PLANS.map(plan=>({...plan}))});
    if (req.method === 'GET' && path === '/api/effects') return json(res,200,{effects:store.state.effectVideos});
    if (req.method === 'POST' && path === '/api/addresses') { const u=requireUser(req,res); if(!u)return; return json(res,201,{address:await store.addAddress(u.id,await body(req))}); }
    if (req.method === 'GET' && path === '/api/addresses') { const u=requireUser(req,res); return u && json(res,200,{addresses:store.state.addresses.filter(a=>a.userId===u.id)}); }
    if (req.method === 'POST' && path === '/api/shipments') { const u=requireUser(req,res); if(!u)return; const b=await body(req); return json(res,201,{shipment:await store.createShipment(u.id,b.userCardIds,b.addressId)}); }
    if (req.method === 'GET' && path === '/api/shipments') { const u=requireUser(req,res); return u && json(res,200,{shipments:store.listShipments({userId:u.id})}); }
    if (req.method === 'GET' && path === '/api/admin/draws') { if(!requireAdmin(req,res))return; const draws=store.searchDraws({userId:url.searchParams.get('userId')||'',packId:url.searchParams.get('packId')||'',from:url.searchParams.get('from')||url.searchParams.get('dateFrom')||'',to:url.searchParams.get('to')||url.searchParams.get('dateTo')||'',rarity:url.searchParams.get('rarity')||''}); return json(res,200,{draws}); }
    if (req.method === 'GET' && path === '/api/admin/draws.csv') {
      if(!requireAdmin(req,res))return;
      const csv = drawLogCsv(store.searchDraws({userId:url.searchParams.get('userId')||'',packId:url.searchParams.get('packId')||'',from:url.searchParams.get('from')||url.searchParams.get('dateFrom')||'',to:url.searchParams.get('to')||url.searchParams.get('dateTo')||'',rarity:url.searchParams.get('rarity')||''}));
      res.writeHead(200, {'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="draws.csv"','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});
      return res.end(csv);
    }
    if (req.method === 'GET' && path === '/api/admin/draws/verify') { if(!requireAdmin(req,res))return; return json(res,200,{valid:store.verifyDrawLog(),count:store.state.draws.length}); }
    if (req.method === 'GET' && path === '/api/admin/users') { const u=requireAdmin(req,res); if(!u)return; const users=store.searchUsers({q:url.searchParams.get('q')||'',email:url.searchParams.get('email')||'',userId:url.searchParams.get('userId')||'',id:url.searchParams.get('id')||'',phone:url.searchParams.get('phone')||''}); return json(res,200,{users:users.map(x=>({...publicUser(x),phone:x.phone||'',status:x.status||'active',createdAt:x.createdAt}))}); }
    if (req.method === 'GET' && path.match(/^\/api\/admin\/users\/[^/]+$/)) { const u=requireAdmin(req,res); if(!u)return; const userId=path.split('/').pop(); return json(res,200,{detail:store.userDetails(userId)}); }
    if (req.method === 'PATCH' && path.match(/^\/api\/admin\/users\/[^/]+$/)) { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const userId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:b.status==='deleted'}); const status=b.status || (b.frozen === true ? 'frozen' : b.frozen === false ? 'active' : ''); if(!status) throw new Error('status is required'); const detail=await store.setUserStatus(userId,status,{adminId:u.id,ip:clientIp(req),reason:b.reason}); return json(res,200,{detail}); }
    if (req.method === 'GET' && path === '/api/admin/inventory') { if(!requireAdmin(req,res))return; return json(res,200,{packs:store.adminInventory()}); }
    if (req.method === 'GET' && path === '/api/admin/anomalies') { if(!requireAdmin(req,res))return; const options={}; for(const key of ['windowMs','minHighValue','threshold']) if(url.searchParams.has(key)) options[key]=Number(url.searchParams.get(key)); return json(res,200,{anomalies:store.detectDrawAnomalies(options)}); }
    if (req.method === 'GET' && path === '/api/admin/audit-logs') { const u=requireAdmin(req,res,{roles:['owner','operator','viewer']}); if(!u)return; return json(res,200,{logs:store.state.adminAuditLogs.map(x=>({...x}))}); }
    if (req.method === 'POST' && path === '/api/admin/admin-users') { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); const created=store.createAdminUser(b); audit(u,req,'admin_user.create',`admin:${created.id}`,null,{id:created.id,email:created.email,role:created.role},b.reason); return json(res,201,{admin:created}); }
    if (req.method === 'PATCH' && path.startsWith('/api/admin/admin-users/')) { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const adminId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); const before=store.state.adminUsers.find(a=>a.id===adminId); if(!before) throw new Error('admin not found'); const updated=store.setAdminIpAllowlist(adminId,b.allowedIps); audit(u,req,'admin_user.ip_allowlist',`admin:${adminId}`,{allowedIps:before.allowedIps},{allowedIps:updated.allowedIps},b.reason); return json(res,200,{admin:updated}); }
    if (req.method === 'GET' && path === '/api/admin/cards') { const u=requireAdmin(req,res); if(!u)return; return json(res,200,{cards:store.adminCards()}); }
    if (req.method === 'GET' && path === '/api/admin/cards.csv') { const u=requireAdmin(req,res); if(!u)return; res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="cards.csv"','cache-control':'no-store','x-content-type-options':'nosniff'}); return res.end(cardCsv(store.state.cards)); }
    if (req.method === 'POST' && path === '/api/admin/cards/import') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true}); const cards=await store.importCardsCsv(b.csv); audit(u,req,'card.import',`cards:batch:${Date.now()}`,null,{count:cards.length},b.reason); return json(res,201,{cards,count:cards.length}); }
    if (req.method === 'POST' && path === '/api/admin/cards') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true}); const card=await store.createCard(b); audit(u,req,'card.create',`card:${card.id}`,null,card,b.reason); return json(res,201,{card}); }
    if (req.method === 'PATCH' && path.startsWith('/api/admin/cards/')) { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const cardId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true}); const before=store.state.cards.find(c=>c.id===cardId); const card=await store.updateCard(cardId,b); audit(u,req,'card.update',`card:${cardId}`,before,card,b.reason); return json(res,200,{card}); }
    if (req.method === 'DELETE' && path.startsWith('/api/admin/cards/')) { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const cardId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); const card=await store.deleteCard(cardId); audit(u,req,'card.delete',`card:${cardId}`,card,null,b.reason); return json(res,200,{card}); }
    if (req.method === 'GET' && path === '/api/admin/packs') { const u=requireAdmin(req,res); if(!u)return; return json(res,200,{packs:store.publicPacks().map(p=>({...p,slotRows:store.state.packs.find(x=>x.id===p.id)?.slotRows||[]}))}); }
    if (req.method === 'GET' && path.match(/^\/api\/admin\/packs\/[^/]+$/)) { const u=requireAdmin(req,res); if(!u)return; const packId=path.split('/').pop(); const pack=store.publicPacks().find(p=>p.id===packId); if(!pack)return json(res,404,{error:'pack not found'}); const draws=store.searchDraws({packId}).map(draw=>{ const user=store.state.users.find(item=>item.id===draw.userId); const card=store.state.cards.find(item=>item.id===draw.cardId); return {...draw,user:{id:draw.userId,email:user?.email||'unknown'},card:card?publicCard(card):{id:draw.cardId,name:'unknown',rarity:draw.rarity}}; }); const purchases=store.state.pointTransactions.filter(tx=>tx.type==='draw'&&tx.metadata?.packId===packId).map(tx=>{ const user=store.state.users.find(item=>item.id===tx.userId); return {id:tx.id,createdAt:tx.createdAt,quantity:tx.metadata.quantity,amount:tx.amount,user:{id:tx.userId,email:user?.email||'unknown'}}; }); return json(res,200,{pack:{...pack,slotRows:store.state.packs.find(p=>p.id===packId)?.slotRows||[]},odds:store.packOdds(packId),lineup:store.packLineup(packId),purchases,draws}); }
    if (req.method === 'POST' && path === '/api/admin/packs') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true}); const pack=await store.createPack(b); audit(u,req,'pack.create',`pack:${pack.id}`,null,pack,b.reason); return json(res,201,{pack}); }
    if (req.method === 'POST' && path.match(/^\/api\/admin\/packs\/[^/]+\/duplicate$/)) { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const packId=path.split('/')[4]; const b=await body(req); adminBodyError(b,{reasonRequired:true}); const pack=await store.duplicatePack(packId,b); audit(u,req,'pack.duplicate',`pack:${pack.id}`,null,{sourcePackId:packId,...pack},b.reason); return json(res,201,{pack}); }
    if (req.method === 'PATCH' && path.startsWith('/api/admin/packs/')) { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const packId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:['stopped','deleted'].includes(b.status)}); const before=store.state.packs.find(p=>p.id===packId); if(!before) throw new Error('pack not found'); const pack=b.status ? await store.updatePackStatus(packId,b.status) : await store.updatePack(packId,b); audit(u,req,b.status?'pack.status':'pack.update',`pack:${packId}`,before,pack,b.reason); return json(res,200,{pack}); }
    if (req.method === 'DELETE' && path.match(/^\/api\/admin\/packs\/[^/]+$/)) { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const packId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); const before=store.state.packs.find(p=>p.id===packId); if(!before) throw new Error('pack not found'); const pack=await store.updatePackStatus(packId,'deleted'); audit(u,req,'pack.delete',`pack:${packId}`,before,pack,b.reason); return json(res,200,{pack}); }
    if (req.method === 'GET' && path === '/api/admin/effect-ranks') { const u=requireAdmin(req,res); if(!u)return; return json(res,200,{ranks:store.state.effectRanks}); }
    if (req.method === 'POST' && path === '/api/admin/effect-ranks') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true}); const rank=await store.setEffectRank(b); audit(u,req,'effect_rank.update',`rank:${rank.name}`,null,rank,b.reason); return json(res,200,{rank}); }
    if (req.method === 'POST' && path === '/api/admin/effects') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true}); const effect=await store.setEffect(b); audit(u,req,'effect.update',`rarity:${effect.rarity}`,null,effect,b.reason); return json(res,200,{effect}); }
    if (req.method === 'GET' && path === '/api/payments') { const u=requireUser(req,res); return u && json(res,200,{payments:store.listPayments(u.id)}); }
    if (req.method === 'POST' && path === '/api/payments') {
      const u=requireUser(req,res); if(!u)return;
      const b=await body(req); const plan=pointPlanById(b.planId);
      if (!plan) throw new Error('invalid point plan');
      // Reject client attempts to override server-owned pricing fields.
      for (const key of ['points','amount','currency']) if (b[key] !== undefined && String(b[key]) !== String(plan[key])) throw new Error('point plan values cannot be changed');
      if (b.stripePaymentId !== undefined && b.stripePaymentId !== null && String(b.stripePaymentId).trim()) throw new Error('provider payment ID cannot be supplied by the client');
      return json(res,201,{payment:await store.createPayment({userId:u.id,points:plan.points,amount:plan.amount,currency:plan.currency,metadata:{planId:plan.id}})});
    }
    if (req.method === 'GET' && path === '/api/site-settings') { return json(res,200,{settings:{...store.state.siteSettings},announcements:store.state.announcements.filter(a=>a.published).map(a=>({...a}))}); }
    if (req.method === 'GET' && path === '/api/admin/shipments') { const u=requireAdmin(req,res,{roles:['owner','operator','viewer']}); if(!u)return; return json(res,200,{shipments:store.listShipments({status:url.searchParams.get('status')||''})}); }
    if (req.method === 'GET' && path === '/api/admin/shipments.csv') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const csv=shipmentLabelCsv(store.listShipments({status:url.searchParams.get('status')||''}),store.state); res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="shipment-labels.csv"','cache-control':'no-store','x-content-type-options':'nosniff'}); return res.end(csv); }
    if (req.method === 'PATCH' && path.startsWith('/api/admin/shipments/')) { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const shipmentId=path.split('/').pop(); const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:['shipped','canceled'].includes(b.status)}); const before=store.state.shipments.find(s=>s.id===shipmentId); if(!before) throw new Error('shipment not found'); const shipment=await store.updateShipment(shipmentId,b); audit(u,req,'shipment.update',`shipment:${shipmentId}`,before,shipment,b.reason); return json(res,200,{shipment}); }
    if (req.method === 'GET' && path === '/api/admin/billing') {
      const u=requireAdmin(req,res); if(!u)return;
      const options = { role:u.role, from:url.searchParams.get('from')||'', to:url.searchParams.get('to')||'', status:url.searchParams.get('status')||'', method:url.searchParams.get('method')||'', provider:url.searchParams.get('provider')||'', userId:url.searchParams.get('userId')||'', email:url.searchParams.get('email')||'', page:Number(url.searchParams.get('page')||1), pageSize:Number(url.searchParams.get('pageSize')||50) };
      const result=store.adminBilling(options); audit(u,req,'payment.list','payments:filtered',null,{filters:result.filters,page:result.page,pageSize:result.pageSize,count:result.payments.length});
      return json(res,200,result);
    }
    if (req.method === 'GET' && path === '/api/admin/payments.csv') {
      const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return;
      const options = { role:'owner', from:url.searchParams.get('from')||'', to:url.searchParams.get('to')||'', status:url.searchParams.get('status')||'', method:url.searchParams.get('method')||'', provider:url.searchParams.get('provider')||'', userId:url.searchParams.get('userId')||'', email:url.searchParams.get('email')||'', page:1, pageSize:100 };
      const billing = store.adminBilling(options); const rows = []; for (let page = 1; page <= billing.totalPages; page++) rows.push(...store.adminBilling({...options,pageSize:100,page}).payments);
      audit(u,req,'payment.export','payments:filtered',null,{count:rows.length,filters:billing.filters});
      res.writeHead(200, {'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="payments-${new Date().toISOString().slice(0,10)}.csv"`,'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});
      return res.end(paymentCsv(rows));
    }
    if (req.method === 'GET' && path.match(/^\/api\/admin\/payments\/[^/]+$/)) {
      const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return;
      const paymentId=path.split('/').pop(); const result=store.adminPaymentDetail(paymentId,{role:u.role}); audit(u,req,'payment.view',`payment:${paymentId}`,null,{paymentId}); return json(res,200,result);
    }
    if (req.method === 'GET' && path === '/api/admin/payments') { const u=requireAdmin(req,res); if(!u)return; const userId=url.searchParams.get('userId')||''; const modernKeys=['from','to','status','method','provider','email','page','pageSize']; const legacy=!modernKeys.some(key=>url.searchParams.has(key)); if(legacy&&u.role==='owner'){ const payments=store.listPayments(userId); audit(u,req,'payment.list','payments:legacy',null,{userId,count:payments.length}); return json(res,200,{payments}); } const options={role:u.role,from:url.searchParams.get('from')||'',to:url.searchParams.get('to')||'',status:url.searchParams.get('status')||'',method:url.searchParams.get('method')||'',provider:url.searchParams.get('provider')||'',userId,page:Number(url.searchParams.get('page')||1),pageSize:Number(url.searchParams.get('pageSize')||50),email:url.searchParams.get('email')||''}; const billing=store.adminBilling(options); audit(u,req,'payment.list','payments:legacy',null,{filters:billing.filters,page:billing.page,pageSize:billing.pageSize,count:billing.payments.length}); return json(res,200,{payments:billing.payments,page:billing.page,pageSize:billing.pageSize,total:billing.total,totalPages:billing.totalPages}); }
    if (req.method === 'POST' && path.match(/^\/api\/admin\/payments\/[^/]+\/mark-paid$/)) { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const paymentId=path.split('/')[3]; const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:false}); return json(res,200,{payment:await store.markPaymentPaid(paymentId,{stripePaymentId:b.stripePaymentId,adminId:u.id,ip:clientIp(req),reason:b.reason})}); }
    if (req.method === 'POST' && path.match(/^\/api\/admin\/payments\/[^/]+\/refund$/)) { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const paymentId=path.split('/')[3]; const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); return json(res,200,{payment:await store.refundPayment(paymentId,{adminId:u.id,ip:clientIp(req),reason:b.reason})}); }
    if (req.method === 'GET' && path === '/api/admin/bank-transfers') { const u=requireAdmin(req,res); if(!u)return; return json(res,200,{transfers:store.state.bankTransfers.map(x=>({...x}))}); }
    if (req.method === 'POST' && path === '/api/bank-transfers') { const u=requireUser(req,res); if(!u)return; const b=await body(req); return json(res,201,{transfer:await store.createBankTransfer({...b,userId:u.id})}); }
    if (req.method === 'POST' && path.match(/^\/api\/admin\/bank-transfers\/[^/]+\/reconcile$/)) { const u=requireAdmin(req,res,{roles:['owner']}); if(!u)return; const transferId=path.split('/')[3]; const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:true}); return json(res,200,{transfer:await store.reconcileBankTransfer(transferId,{userId:b.userId,adminId:u.id,ip:clientIp(req),reason:b.reason})}); }
    if (req.method === 'GET' && path === '/api/admin/dashboard') { if(!requireAdmin(req,res))return; return json(res,200,store.dashboard({from:url.searchParams.get('from')||'',to:url.searchParams.get('to')||''})); }
    if (req.method === 'PATCH' && path === '/api/admin/site-settings') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true,destructive:Boolean(b.maintenance===true)}); return json(res,200,{settings:await store.updateSiteSettings(b,{adminId:u.id,ip:clientIp(req),reason:b.reason})}); }
    if (req.method === 'POST' && path === '/api/admin/announcements') { const u=requireAdmin(req,res,{roles:['owner','operator']}); if(!u)return; const b=await body(req); adminBodyError(b,{reasonRequired:true}); return json(res,200,{announcement:await store.upsertAnnouncement(b,{adminId:u.id,ip:clientIp(req),reason:b.reason})}); }
    if (req.method === 'GET' && (path === '/' || path === '/admin' || path === '/admin/')) { const surface=path === '/'?'user':'admin'; res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-robots-tag':surface==='admin'?'noindex, nofollow':'index, follow','content-security-policy':"default-src 'self'; img-src 'self' data:; media-src 'self' https:; script-src 'unsafe-inline'; style-src 'unsafe-inline'"}); return res.end(surfaceHtml(surface)); }
    json(res,404,{error:'not found'});
  } catch (e) { const status = /invalid credentials|invalid admin credentials|2FA verification required/.test(e.message) ? 401 : /IP not allowed|insufficient admin role|admin account must use/.test(e.message) ? 403 : 400; json(res, status, {error:e.userMessage || e.message, ...(e.code ? {code:e.code} : {})}); }
});
function odds(storeLike, packId) { const slots=storeLike.state.packSlots.filter(s=>s.packId===packId); const counts={}; for(const s of slots)counts[s.rarity]=(counts[s.rarity]||0)+1; return Object.fromEntries(Object.entries(counts).map(([rarity,count])=>[rarity,{count,total:slots.length,probability:`${count}/${slots.length}`}])) }
function lineup(storeLike, packId) { const slots=storeLike.state.packSlots.filter(s=>s.packId===packId); const counts=new Map(); for (const slot of slots) counts.set(slot.cardId,(counts.get(slot.cardId)||0)+1); return [...counts].map(([cardId,count])=>({card:publicCard(storeLike.state.cards.find(c=>c.id===cardId)),count})).sort((a,b)=>rarityRank(b.card.rarity)-rarityRank(a.card.rarity)); }
function rarityRank(rarity) { return ({N:0,R:1,SR:2,SSR:3})[rarity] ?? -1; }

if (process.env.NODE_ENV !== 'test') server.listen(port, () => console.log(`gacha server listening on http://localhost:${port}`));
export { server, store };
